---
# https://github.com/alphagov/tech-docs-gem/blob/main/example/config/tech-docs.yml

host: https://ministryofjustice.github.io/template-documentation-site
show_govuk_logo: false
service_name: Template Documentation Site
service_link: /
header_links:
enable_search: true
collapsible_nav: true
max_toc_heading_level: 3
prevent_indexing: true
show_contribution_banner: true
github_repo: ministryofjustice/template-documentation-site
github_branch: main
full_service_name: Template Documentation Site
show_expiry: true
show_review_banner: true
