name: Check for broken links

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.1
    steps:
    - uses: actions/checkout@v2
    - name: htmlproofer
      run: /publishing-scripts/publish.sh no-repository-changes
