---
name: Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/tech-docs-github-pages-publisher@sha256:7c0508cf2d199c1b3f0f67e4872023d5399425fead9b2bb2ca461f72c5f409a3 # v6.2.0-1
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Build
        id: build
        run: |
          /usr/local/bin/package
